### ISSUE TITLE
Incompatible to recent pinyin-utils

### ISSUE THREAD

**Issue by McShelby** [pepebecker/pinyin-or-hanzi#6]
In https://github.com/pepebecker/pinyin-utils/commit/4973735f0a5e6af3ff42964c79d1151d461ac935 the exported `tones` array was renamed to `toneMarks` but is still referenced by its old name inside of this package

**Comment by pepebecker** [comment]
@McShelby this should be fixed in the latest of this module. I also increased the major version of pinyin-utils due to the breaking change
